### ISSUE TITLE
Super Noob question - sorry!

### ISSUE THREAD

**Issue by GregKeaney** [Sitebase/tinymce-variable#22]
Sorry to be a mega noob on this but;

I think this is exactly what I need for my TinyMCE implementation.  However, I can't see any docs on how to include this.  This is my first TinyMCE project so I am kinda in the dark.  I can see how to add it tothe list of plugins, where do I add the actual plugin source?

**Comment by GregKeaney** [comment]
Sorry. RTFM!  https://www.tinymce.com/docs/advanced/creating-a-plugin/

**Comment by Sitebase** [comment]
@GregKeaney do keep in mind that this is not really production ready. We are still working on this at the moment.
