### ISSUE TITLE
Last item variable

### ISSUE THREAD

**Issue by Sitebase** [Sitebase/tinymce-variable#4]
When the last item in the editor is a variable you can't do space to start typing behind that variable.

**Comment by mahammedzkhan** [comment]
I've been able to partially fix this issue by using collapse as stated in the TinyMCE API:
http://www.tinymce.com/wiki.php/api4:method.tinymce.dom.Selection.collapse

But this causes an issue with the 'enter' key not working in Chrome (works fine in Firefox).

These are the two lines that I've added:
editor.selection.select(editor.getBody(), true);
editor.selection.collapse(false);

**Comment by mahammedzkhan** [comment]
This space bug is also only present in Chrome, works fine in Firefox and IE11.

**Comment by Sitebase** [comment]
This issue seems to get fixed by https://github.com/bubobox/tinymce-variable/issues/11

**Comment by Sitebase** [comment]
Fixed by adding `contentEditable`
